'use client';
import { useMemo, useState } from 'react';
import type { InventorySnapshot } from '../lib/db/contracts';
import { useInventoryActions } from '../lib/hooks/useInventoryActions';

type Line={productId:string;quantity:number};
export function CustomerOrderPanel({inventory,onChanged}:{inventory:InventorySnapshot[];onChanged:()=>Promise<void>|void}){
 const actions=useInventoryActions(onChanged); const [customer,setCustomer]=useState(''); const [phone,setPhone]=useState(''); const [productId,setProductId]=useState(inventory[0]?.productId??''); const [qty,setQty]=useState(1); const [lines,setLines]=useState<Line[]>([]); const [message,setMessage]=useState('');
 const selected=inventory.find(x=>x.productId===productId); const total=useMemo(()=>lines.reduce((s,x)=>s+x.quantity,0),[lines]);
 function add(){if(!selected)return;const existing=lines.find(x=>x.productId===productId);const next=(existing?.quantity??0)+qty;if(qty<1||next>selected.available)return setMessage(`Only ${selected.available} available.`);setLines(existing?lines.map(x=>x.productId===productId?{...x,quantity:next}:x):[...lines,{productId,quantity:qty}]);setQty(1);setMessage('')}
 async function reserve(){if(!customer.trim())return setMessage('Enter customer name.');if(!lines.length)return setMessage('Add at least one item.');const ok=await actions.reserveOrder({customerName:customer.trim(),customerPhone:phone.trim()||undefined,items:lines});if(ok){setCustomer('');setPhone('');setLines([]);setMessage('Order reserved. Inventory will deduct when the order is physically pulled.')}else setMessage(actions.message||'Could not reserve order.');}
 return <section className="card"><div className="card-head"><div><p className="eyebrow">PHONE ORDER</p><h2>Customer order</h2></div></div><div className="form"><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/></label><label>Phone (optional)<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone"/></label><div className="form-row"><label>Ice cream<select value={productId} onChange={e=>setProductId(e.target.value)}>{inventory.map(x=><option key={x.productId} value={x.productId}>{x.flavor} · {x.packageSize==='3_GALLON'?'3 gal':'48 oz'} · {x.available} available</option>)}</select></label><label>Qty<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label></div><button onClick={add}>+ Add to order</button><div className="cart-lines">{lines.map(l=>{const p=inventory.find(x=>x.productId===l.productId)!;return <div className="order-row" key={l.productId}><div><strong>{p.flavor} · {p.packageSize==='3_GALLON'?'3 gal':'48 oz'}</strong><small>{l.quantity} unit{l.quantity===1?'':'s'}</small></div><button onClick={()=>setLines(lines.filter(x=>x.productId!==l.productId))}>Remove</button></div>})}</div><button className="primary" disabled={actions.state==='working'||!lines.length} onClick={reserve}>{actions.state==='working'?'Reserving…':`Reserve Order · ${total} unit${total===1?'':'s'}`}</button>{message&&<p className="helper">{message}</p>}</div></section>
}
