'use client';
import { useMemo, useState } from 'react';
import type { InventorySnapshot } from '../lib/db/contracts';
import { useInventoryActions } from '../lib/hooks/useInventoryActions';

type Line={productId:string;quantity:number};
export function CustomerOrderPanel({inventory,onChanged}:{inventory:InventorySnapshot[];onChanged:()=>Promise<void>|void}){
 const actions=useInventoryActions(); const [customer,setCustomer]=useState(''); const [phone,setPhone]=useState(''); const [productId,setProductId]=useState(inventory[0]?.productId??''); const [qty,setQty]=useState(1); const [lines,setLines]=useState<Line[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const selected=inventory.find(x=>x.productId===productId); const total=useMemo(()=>lines.reduce((s,x)=>s+x.quantity,0),[lines]);
 function add(){if(!selected)return;const existing=lines.find(x=>x.productId===productId);const next=(existing?.quantity??0)+qty;if(qty<1||next>selected.available)return setMessage(`Only ${selected.available} available.`);setLines(existing?lines.map(x=>x.productId===productId?{...x,quantity:next}:x):[...lines,{productId,quantity:qty}]);setQty(1);setMessage('')}
 async function reserve(){try{if(!customer.trim())throw new Error('Enter customer name.');if(!lines.length)throw new Error('Add at least one item.');setBusy(true);const r=await actions.createOrder({customerName:customer.trim(),customerPhone:phone.trim()||undefined,items:lines});await onChanged();setCustomer('');setPhone('');setLines([]);setMessage(`Order ${r.orderId.slice(0,8)} reserved. Inventory deducts only when pulled.`)}catch(e:any){setMessage(e.message??'Could not reserve order.')}finally{setBusy(false)}}
 return <section className="card"><div className="card-head"><div><p className="eyebrow">PHONE ORDER</p><h2>Customer order</h2></div></div><div className="form"><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/></label><label>Phone (optional)<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone"/></label><div className="form-row"><label>Ice cream<select value={productId} onChange={e=>setProductId(e.target.value)}>{inventory.map(x=><option key={x.productId} value={x.productId}>{x.flavor} · {x.packageSize==='3_GALLON'?'3 gal':'48 oz'} · {x.available} available</option>)}</select></label><label>Qty<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label></div><button onClick={add}>+ Add to order</button><div className="cart-lines">{lines.map(l=>{const p=inventory.find(x=>x.productId===l.productId)!;return <div className="order-row" key={l.productId}><div><strong>{p.flavor} · {p.packageSize==='3_GALLON'?'3 gal':'48 oz'}</strong><small>{l.quantity} unit{l.quantity===1?'':'s'}</small></div><button onClick={()=>setLines(lines.filter(x=>x.productId!==l.productId))}>Remove</button></div>})}</div><button className="primary" disabled={busy||!lines.length} onClick={reserve}>{busy?'Reserving…':`Reserve Order · ${total} unit${total===1?'':'s'}`}</button>{message&&<p className="helper">{message}</p>}</div></section>
}
