'use client';
import { useState } from 'react';
import type { InventorySnapshot, PackageSizeDb } from '../lib/db/contracts';
import { useInventoryActions } from '../lib/hooks/useInventoryActions';

export function ProductionPanel({ inventory, onChanged }:{inventory:InventorySnapshot[];onChanged:()=>Promise<void>|void}){
 const actions=useInventoryActions(); const flavors=[...new Set(inventory.map(x=>x.flavor))];
 const [julian,setJulian]=useState(''); const [flavor,setFlavor]=useState(flavors[0]??''); const [size,setSize]=useState<PackageSizeDb>('3_GALLON'); const [total,setTotal]=useState(1); const [storefront,setStorefront]=useState(0); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 async function submit(){try{setBusy(true);setMessage('');const j=Number(julian);if(!Number.isInteger(j)||j<1||j>366)throw new Error('Julian date must be 1–366.');if(total<1||storefront<0||storefront>total)throw new Error('Check the quantities.');const r=await actions.addProduction({julian:j,flavor,packageSize:size,totalProduced:total,storefrontQuantity:storefront});await onChanged();setTotal(1);setStorefront(0);setMessage(`Added. ${total-storefront} to -40°F hold and ${storefront} to Storefront. Run ${r.runId.slice(0,8)}.`)}catch(e:any){setMessage(e.message??'Could not add production.')}finally{setBusy(false)}}
 return <section className="card"><div className="card-head"><div><p className="eyebrow">PROCESSING DAY</p><h2>Add production</h2></div></div><div className="form"><label>Julian date<input inputMode="numeric" value={julian} onChange={e=>setJulian(e.target.value)} placeholder="238"/></label><div className="form-row"><label>Flavor<select value={flavor} onChange={e=>setFlavor(e.target.value)}>{flavors.map(x=><option key={x}>{x}</option>)}</select></label><label>Package<select value={size} onChange={e=>setSize(e.target.value as PackageSizeDb)}><option value="3_GALLON">3 gal</option><option value="48_OZ">48 oz</option></select></label></div><div className="form-row"><label>Total produced<input type="number" min="1" value={total} onChange={e=>setTotal(Number(e.target.value))}/></label><label>Storefront / imperfect<input type="number" min="0" value={storefront} onChange={e=>setStorefront(Number(e.target.value))}/></label></div><div className="production-split"><b>{Math.max(0,total-storefront)} good</b> → -40°F hold &nbsp; <b>{storefront}</b> → Storefront</div><button className="primary" disabled={busy||!flavor} onClick={submit}>{busy?'Saving…':'Add Production'}</button>{message&&<p className="helper">{message}</p>}</div></section>
}
